# User Deployment 配置
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
spec:
  replicas: 2  # 初始副本数量
  selector:
    matchLabels:
      app: course  # Pod 选择器标签
  template:
    metadata:
      labels:
        app: course # Pod 标签
    spec:
      containers:
        - name: user-container
          image: frosky/server:latest  # 容器镜像
          ports:
            - containerPort: 9977  # 容器端口
---
# User Service 配置
apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  selector:
    app: user  # 选择与 Deployment 中匹配的 Pod
  ports:
    - protocol: TCP
      port: 80  # Service 端口
      targetPort: 7073  # Pod 的目标端口
  type: ClusterIP  # 内部集群 IP
---
# User Horizontal Pod Autoscaler 配置
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-deployment  # 目标 Deployment
  minReplicas: 1  # 最小副本数量
  maxReplicas: 10  # 最大副本数量
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # CPU 使用率阈值
