server:
  port: 9983

spring:
  application:
    name: auth-filter
  profiles:
    active: dev, resource-nonpublic-dev, self-nonpublic-dev
#    active: prod, resource-nonpublic-prod, self-nonpublic-prod
