# User Deployment 配置
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-push-deployment
spec:
  replicas: 2  # 初始副本数量
  selector:
    matchLabels:
      app: msg-push  # Pod 选择器标签
  template:
    metadata:
      labels:
        app: msg-push # Pod 标签
    spec:
      containers:
        - name: msg-push-container
          image: frosky/ooad-msg-push-server:latest  # 容器镜像
          ports:
            - containerPort: 9983  # 容器端口
---
# User Service 配置
apiVersion: v1
kind: Service
metadata:
  name: msg-push-svc
  namespace: default
spec:
  selector:
    app: msg-push  # 选择与 Deployment 中匹配的 Pod
  ports:
    - protocol: TCP
      port: 9983  # Service 端口
      targetPort: 9983  # Pod 的目标端口
  type: ClusterIP  # 内部集群 IP
---
# User Horizontal Pod Autoscaler 配置
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: msg-push-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: msg-push-deployment  # 目标 Deployment
  minReplicas: 1  # 最小副本数量
  maxReplicas: 10  # 最大副本数量
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # CPU 使用率阈值
